apiVersion: v1
kind: Service
metadata:
  name: springboot-web-svc
spec:
  ports:
  - name: sw
    protocol: TCP
    port: 8080
    targetPort: 8080
  clusterIP: None
  selector:
    app: springboot-web
